name: Static analysis
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  types-check:
    name: Typescript check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
      - name: Install dependencies
        run: npm install
      - name: Typescript check
        run: npm run types:check
